#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 30 09:48:50 2021

@author: pikachu
"""

class A():
    
    def __init__(self,  a,b):
        self.a = int(a)
        self.b = int(b)
        
    def mul(self):
        return self.a*self.b
    
    def add(self):
        return self.a + self.b
    
    def sub(self):
        return self.a - self.b
    

class B(A):
    
    def div(self, a , b):
        return (a//b)
    

count = B()
print(count.square(3))
