#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 18 14:22:57 2022

@author: pikachu
"""
import os
from selenium import webdriver  
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By # new one
from selenium.webdriver.chrome.service import Service #new one


PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
DRIVER_BIN = os.path.join(PROJECT_ROOT, "chromedriver")

s = Service(DRIVER_BIN)
browser = webdriver.Chrome(service=s) #to solve the commands are deprecated.

browser.get('https://2048game.com/')
browser.maximize_window()
#linkElem = browser.find_element_by_link_text('Automate the Boring Stuff with Python')
#linkElem.click()
htmlElem = browser.find_element(By.TAG_NAME,'html')     #按鍵都傳給他 改成用Ｂy
#htmlElem.send_keys(Keys.PAGE_DOWN)

for i in range(100):

    htmlElem.send_keys(Keys.DOWN)
    htmlElem.send_keys(Keys.RIGHT)
    htmlElem.send_keys(Keys.LEFT)
    htmlElem.send_keys(Keys.UP)